[ req ]
default_bits       = 4096
default_keyfile    = ca.key
distinguished_name = req_distinguished_name
req_extensions     = req_ext
prompt             = no
input_password     = password
output_password    = password

[ req_distinguished_name ]
C  = SG
ST = Singapore
L  = Singapore
O  = Elk
OU = SA
CN = customized.ca.local
emailAddress = sa@elastic.local

[ req_ext ]
subjectAltName = @alt_names
basicConstraints = critical,CA:TRUE
keyUsage = critical,keyCertSign,cRLSign
# critical means Any client that does not understand this extension MUST reject the certificate.

[ alt_names ]
DNS.1 = dockerca.docker.local
email.1 = ming.shen@elastic.local
