[ req ]
default_bits       = 4096
default_keyfile    = server.key
distinguished_name = req_distinguished_name
req_extensions     = req_ext
prompt             = no
input_password     = password
output_password    = password

[ req_distinguished_name ]
C  = SG
ST = Singapore
L  = Singapore
O  = Elk
OU = SA
CN = kibana1
emailAddress = sa@elatic.local

[ req_ext ]
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = esfrozen01
DNS.2 = eshot01
DNS.3 = eshot02
DNS.4 = eshot03
DNS.5 = kibana2
DNS.6 = fleet
DNS.7 = localhost
IP.1 = 127.0.0.1
email.1 = ming.shen@elastic.local
